package com.vladsch.flexmark.formatter.internal;

import com.vladsch.flexmark.formatter.Formatter;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.parser.ParserEmulationProfile;
import com.vladsch.flexmark.util.data.DataHolder;
import com.vladsch.flexmark.util.format.CharWidthProvider;
import com.vladsch.flexmark.util.format.options.*;

public class FormatterOptions {
    public final boolean itemContentIndent;

    public final ParserEmulationProfile emulationProfile;
    public final boolean setextHeaderEqualizeMarker;
    public final int formatFlags;
    public final int maxBlankLines;
    public final int maxTrailingBlankLines;
    public final int rightMargin;
    public final int minSetextMarkerLength;
    public final DiscretionaryText spaceAfterAtxMarker;
    public final EqualizeTrailingMarker atxHeaderTrailingMarker;
    public final boolean blockQuoteBlankLines;
    public final BlockQuoteMarker blockQuoteMarkers;
    public final String thematicBreak;
    public final String translationIdFormat;
    public final String translationHtmlBlockPrefix;
    public final String translationHtmlInlinePrefix;
    public final String translationExcludePattern;
    public final String translationHtmlBlockTagPattern;
    public final String translationHtmlInlineTagPattern;
    public final String translationAutolinkPrefix;
    public final boolean indentedCodeMinimizeIndent;
    public final boolean fencedCodeMinimizeIndent;
    public final boolean fencedCodeMatchClosingMarker;
    public final boolean fencedCodeSpaceBeforeInfo;
    public final int fencedCodeMarkerLength;
    public final CodeFenceMarker fencedCodeMarkerType;
    public final boolean listAddBlankLineBefore;
    //public final boolean listAlignFirstLineText;
    //public final boolean listAlignChildBlocks;
    public final boolean listRenumberItems;
    public final boolean listRemoveEmptyItems;
    public final ListBulletMarker listBulletMarker;
    public final ListNumberedMarker listNumberedMarker;
    public final ListSpacing listSpacing;
    public final ElementPlacement referencePlacement;
    public final ElementPlacementSort referenceSort;
    public final boolean keepImageLinksAtStart;
    public final boolean keepExplicitLinksAtStart;
    public final boolean keepHardLineBreaks;
    public final boolean keepSoftLineBreaks;
    public final boolean appendTransferredReferences;
    public final boolean optimizedInlineRendering;
    public final boolean applySpecialLeadInHandlers;
    public final CharWidthProvider charWidthProvider;
    //public final TrailingSpaces keepTrailingSpaces;
    //public final TrailingSpaces codeKeepTrailingSpaces;

    public FormatterOptions(DataHolder options) {
        emulationProfile = Formatter.FORMATTER_EMULATION_PROFILE.get(options);
        itemContentIndent = emulationProfile.family != ParserEmulationProfile.FIXED_INDENT;

        setextHeaderEqualizeMarker = Formatter.SETEXT_HEADER_EQUALIZE_MARKER.get(options);
        formatFlags = Formatter.FORMAT_FLAGS.get(options);
        maxBlankLines = Formatter.MAX_BLANK_LINES.get(options);
        maxTrailingBlankLines = Formatter.MAX_TRAILING_BLANK_LINES.get(options);
        rightMargin = Formatter.RIGHT_MARGIN.get(options);
        minSetextMarkerLength = Parser.HEADING_SETEXT_MARKER_LENGTH.get(options);
        spaceAfterAtxMarker = Formatter.SPACE_AFTER_ATX_MARKER.get(options);
        atxHeaderTrailingMarker = Formatter.ATX_HEADER_TRAILING_MARKER.get(options);
        thematicBreak = Formatter.THEMATIC_BREAK.get(options);
        translationIdFormat = Formatter.TRANSLATION_ID_FORMAT.get(options);
        translationHtmlBlockPrefix = Formatter.TRANSLATION_HTML_BLOCK_PREFIX.get(options);
        translationHtmlInlinePrefix = Formatter.TRANSLATION_HTML_INLINE_PREFIX.get(options);
        translationAutolinkPrefix = Formatter.TRANSLATION_AUTOLINK_PREFIX.get(options);
        translationExcludePattern = Formatter.TRANSLATION_EXCLUDE_PATTERN.get(options);
        translationHtmlBlockTagPattern = Formatter.TRANSLATION_HTML_BLOCK_TAG_PATTERN.get(options);
        translationHtmlInlineTagPattern = Formatter.TRANSLATION_HTML_INLINE_TAG_PATTERN.get(options);
        blockQuoteBlankLines = Formatter.BLOCK_QUOTE_BLANK_LINES.get(options);
        blockQuoteMarkers = Formatter.BLOCK_QUOTE_MARKERS.get(options);
        indentedCodeMinimizeIndent = Formatter.INDENTED_CODE_MINIMIZE_INDENT.get(options);
        fencedCodeMinimizeIndent = Formatter.FENCED_CODE_MINIMIZE_INDENT.get(options);
        fencedCodeMatchClosingMarker = Formatter.FENCED_CODE_MATCH_CLOSING_MARKER.get(options);
        fencedCodeSpaceBeforeInfo = Formatter.FENCED_CODE_SPACE_BEFORE_INFO.get(options);
        fencedCodeMarkerLength = Formatter.FENCED_CODE_MARKER_LENGTH.get(options);
        fencedCodeMarkerType = Formatter.FENCED_CODE_MARKER_TYPE.get(options);
        listAddBlankLineBefore = Formatter.LIST_ADD_BLANK_LINE_BEFORE.get(options);
        //listAlignFirstLineText = Formatter.LIST_ALIGN_FIRST_LINE_TEXT.getFrom(options);
        //listAlignChildBlocks = Formatter.LIST_ALIGN_CHILD_BLOCKS.getFrom(options);
        listRenumberItems = Formatter.LIST_RENUMBER_ITEMS.get(options);
        listRemoveEmptyItems = Formatter.LIST_REMOVE_EMPTY_ITEMS.get(options);
        listBulletMarker = Formatter.LIST_BULLET_MARKER.get(options);
        listNumberedMarker = Formatter.LIST_NUMBERED_MARKER.get(options);
        listSpacing = Formatter.LIST_SPACING.get(options);
        referencePlacement = Formatter.REFERENCE_PLACEMENT.get(options);
        referenceSort = Formatter.REFERENCE_SORT.get(options);
        keepImageLinksAtStart = Formatter.KEEP_IMAGE_LINKS_AT_START.get(options);
        keepExplicitLinksAtStart = Formatter.KEEP_EXPLICIT_LINKS_AT_START.get(options);
        charWidthProvider = Formatter.FORMAT_CHAR_WIDTH_PROVIDER.get(options);
        keepHardLineBreaks = Formatter.KEEP_HARD_LINE_BREAKS.get(options);
        keepSoftLineBreaks = Formatter.KEEP_SOFT_LINE_BREAKS.get(options);
        appendTransferredReferences = Formatter.APPEND_TRANSFERRED_REFERENCES.get(options);
        optimizedInlineRendering = Formatter.OPTIMIZED_INLINE_RENDERING.get(options);
        applySpecialLeadInHandlers = Formatter.APPLY_SPECIAL_LEAD_IN_HANDLERS.get(options);
        //keepTrailingSpaces = Formatter.KEEP_TRAILING_SPACES.getFrom(options);
        //codeKeepTrailingSpaces = Formatter.CODE_KEEP_TRAILING_SPACES.getFrom(options);
    }
}
