package com.vladsch.flexmark.convert.html;

import com.vladsch.flexmark.util.Utils;
import com.vladsch.flexmark.util.format.TableFormatOptions;
import com.vladsch.flexmark.util.html.CellAlignment;
import com.vladsch.flexmark.util.data.DataHolder;
import com.vladsch.flexmark.util.data.MutableDataHolder;
import com.vladsch.flexmark.util.data.MutableDataSetter;

import java.util.Map;
import java.util.regex.Pattern;

@SuppressWarnings({ "WeakerAccess", "deprecation" })
public class HtmlParserOptions implements MutableDataSetter {
    public boolean listContentIndent;
    public boolean setextHeadings;
    public boolean outputUnknownTags;
    public boolean typographicQuotes;
    public boolean typographicSmarts;
    public boolean outputAttributesIdAttr;
    public boolean wrapAutoLinks;
    public boolean extractAutoLinks;
    public boolean renderComments;
    public boolean dotOnlyNumericLists;
    public boolean commentOriginalNonNumericListItem;
    public boolean preCodePreserveEmphasis;
    public boolean listsEndOnDoubleBlank;
    public boolean divAsParagraph;
    public boolean brAsParaBreaks;
    public boolean brAsExtraBlankLines;
    public boolean ignoreTableHeadingAfterRows;
    public boolean addTrailingEol;
    public boolean skipInlineStrong;
    public boolean skipInlineEmphasis;
    public boolean skipInlineCode;
    public boolean skipInlineDel;
    public boolean skipInlineIns;
    public boolean skipInlineSub;
    public boolean skipInlineSup;
    public boolean skipHeading1;
    public boolean skipHeading2;
    public boolean skipHeading3;
    public boolean skipHeading4;
    public boolean skipHeading5;
    public boolean skipHeading6;
    public boolean skipAttributes;
    public boolean skipFencedCode;
    public boolean skipLinks;
    public boolean skipCharEscape;
    public ExtensionConversion extInlineStrong;
    public ExtensionConversion extInlineEmphasis;
    public ExtensionConversion extInlineCode;
    public ExtensionConversion extInlineDel;
    public ExtensionConversion extInlineIns;
    public ExtensionConversion extInlineSub;
    public ExtensionConversion extInlineSup;
    public ExtensionConversion extMath;
    public ExtensionConversion extTables;
    public LinkConversion extInlineLink;
    public LinkConversion extInlineImage;
    public char orderedListDelimiter;
    public char unorderedListDelimiter;
    public int definitionMarkerSpaces;
    public int minSetextHeadingMarkerLength;
    public String codeIndent;
    public String eolInTitleAttribute;
    public String nbspText;
    public String thematicBreak;
    public String outputAttributesNamesRegex;
    public Pattern outputAttributesNamesRegexPattern;
    public String outputIdAttributeRegex;
    public Pattern outputIdAttributeRegexPattern;
    public Map<Object, CellAlignment> tableCellAlignmentMap;
    public TableFormatOptions tableOptions;

    HtmlParserOptions() {
        this((DataHolder) null);
    }

    HtmlParserOptions(HtmlParserOptions other) {
        listContentIndent = other.listContentIndent;
        setextHeadings = other.setextHeadings;
        outputUnknownTags = other.outputUnknownTags;
        typographicQuotes = other.typographicQuotes;
        typographicSmarts = other.typographicSmarts;
        outputAttributesIdAttr = other.outputAttributesIdAttr;
        wrapAutoLinks = other.wrapAutoLinks;
        extractAutoLinks = other.extractAutoLinks;
        renderComments = other.renderComments;
        dotOnlyNumericLists = other.dotOnlyNumericLists;
        commentOriginalNonNumericListItem = other.commentOriginalNonNumericListItem;
        preCodePreserveEmphasis = other.preCodePreserveEmphasis;
        listsEndOnDoubleBlank = other.listsEndOnDoubleBlank;
        divAsParagraph = other.divAsParagraph;
        brAsParaBreaks = other.brAsParaBreaks;
        brAsExtraBlankLines = other.brAsExtraBlankLines;
        ignoreTableHeadingAfterRows = other.ignoreTableHeadingAfterRows;
        addTrailingEol = other.addTrailingEol;
        skipInlineStrong = other.skipInlineStrong;
        skipInlineEmphasis = other.skipInlineEmphasis;
        skipInlineCode = other.skipInlineCode;
        skipInlineDel = other.skipInlineDel;
        skipInlineIns = other.skipInlineIns;
        skipInlineSub = other.skipInlineSub;
        skipInlineSup = other.skipInlineSup;
        skipHeading1 = other.skipHeading1;
        skipHeading2 = other.skipHeading2;
        skipHeading3 = other.skipHeading3;
        skipHeading4 = other.skipHeading4;
        skipHeading5 = other.skipHeading5;
        skipHeading6 = other.skipHeading6;
        skipAttributes = other.skipAttributes;
        skipFencedCode = other.skipFencedCode;
        skipLinks = other.skipLinks;
        skipCharEscape = other.skipCharEscape;
        extInlineStrong = other.extInlineStrong;
        extInlineEmphasis = other.extInlineEmphasis;
        extInlineCode = other.extInlineCode;
        extInlineDel = other.extInlineDel;
        extInlineIns = other.extInlineIns;
        extInlineSub = other.extInlineSub;
        extInlineSup = other.extInlineSup;
        orderedListDelimiter = other.orderedListDelimiter;
        unorderedListDelimiter = other.unorderedListDelimiter;
        definitionMarkerSpaces = other.definitionMarkerSpaces;
        minSetextHeadingMarkerLength = other.minSetextHeadingMarkerLength;
        codeIndent = other.codeIndent;
        eolInTitleAttribute = other.eolInTitleAttribute;
        nbspText = other.nbspText;
        thematicBreak = other.thematicBreak;
        outputAttributesNamesRegex = other.outputAttributesNamesRegex;
        outputAttributesNamesRegexPattern = other.outputAttributesNamesRegexPattern;
        tableCellAlignmentMap = other.tableCellAlignmentMap;
        tableOptions = other.tableOptions;
        outputIdAttributeRegex = other.outputIdAttributeRegex;
        outputIdAttributeRegexPattern = other.outputIdAttributeRegexPattern;
        extMath = other.extMath;
        extTables = other.extTables;
        extInlineLink = other.extInlineLink;
        extInlineImage = other.extInlineImage;
    }

    HtmlParserOptions(DataHolder options) {
        listContentIndent = FlexmarkHtmlParser.LIST_CONTENT_INDENT.getFrom(options);
        setextHeadings = FlexmarkHtmlParser.SETEXT_HEADINGS.getFrom(options);
        outputUnknownTags = FlexmarkHtmlParser.OUTPUT_UNKNOWN_TAGS.getFrom(options);
        typographicQuotes = FlexmarkHtmlParser.TYPOGRAPHIC_QUOTES.getFrom(options);
        typographicSmarts = FlexmarkHtmlParser.TYPOGRAPHIC_SMARTS.getFrom(options);
        outputAttributesIdAttr = FlexmarkHtmlParser.OUTPUT_ATTRIBUTES_ID.getFrom(options);
        wrapAutoLinks = FlexmarkHtmlParser.WRAP_AUTO_LINKS.getFrom(options);
        extractAutoLinks = FlexmarkHtmlParser.EXTRACT_AUTO_LINKS.getFrom(options);
        renderComments = FlexmarkHtmlParser.RENDER_COMMENTS.getFrom(options);
        dotOnlyNumericLists = FlexmarkHtmlParser.DOT_ONLY_NUMERIC_LISTS.getFrom(options);
        commentOriginalNonNumericListItem = FlexmarkHtmlParser.COMMENT_ORIGINAL_NON_NUMERIC_LIST_ITEM.getFrom(options);
        preCodePreserveEmphasis = FlexmarkHtmlParser.PRE_CODE_PRESERVE_EMPHASIS.getFrom(options);
        listsEndOnDoubleBlank = FlexmarkHtmlParser.LISTS_END_ON_DOUBLE_BLANK.getFrom(options);
        divAsParagraph = FlexmarkHtmlParser.DIV_AS_PARAGRAPH.getFrom(options);
        brAsParaBreaks = FlexmarkHtmlParser.BR_AS_PARA_BREAKS.getFrom(options);
        brAsExtraBlankLines = FlexmarkHtmlParser.BR_AS_EXTRA_BLANK_LINES.getFrom(options);
        ignoreTableHeadingAfterRows = FlexmarkHtmlParser.IGNORE_TABLE_HEADING_AFTER_ROWS.getFrom(options);
        addTrailingEol = FlexmarkHtmlParser.ADD_TRAILING_EOL.getFrom(options);
        skipInlineStrong = FlexmarkHtmlParser.SKIP_INLINE_STRONG.getFrom(options);
        skipInlineEmphasis = FlexmarkHtmlParser.SKIP_INLINE_EMPHASIS.getFrom(options);
        skipInlineCode = FlexmarkHtmlParser.SKIP_INLINE_CODE.getFrom(options);
        skipInlineDel = FlexmarkHtmlParser.SKIP_INLINE_DEL.getFrom(options);
        skipInlineIns = FlexmarkHtmlParser.SKIP_INLINE_INS.getFrom(options);
        skipInlineSub = FlexmarkHtmlParser.SKIP_INLINE_SUB.getFrom(options);
        skipInlineSup = FlexmarkHtmlParser.SKIP_INLINE_SUP.getFrom(options);
        skipHeading1 = FlexmarkHtmlParser.SKIP_HEADING_1.getFrom(options);
        skipHeading2 = FlexmarkHtmlParser.SKIP_HEADING_2.getFrom(options);
        skipHeading3 = FlexmarkHtmlParser.SKIP_HEADING_3.getFrom(options);
        skipHeading4 = FlexmarkHtmlParser.SKIP_HEADING_4.getFrom(options);
        skipHeading5 = FlexmarkHtmlParser.SKIP_HEADING_5.getFrom(options);
        skipHeading6 = FlexmarkHtmlParser.SKIP_HEADING_6.getFrom(options);
        skipAttributes = FlexmarkHtmlParser.SKIP_ATTRIBUTES.getFrom(options);
        skipFencedCode = FlexmarkHtmlParser.SKIP_FENCED_CODE.getFrom(options);
        skipLinks = FlexmarkHtmlParser.SKIP_LINKS.getFrom(options);
        skipCharEscape = FlexmarkHtmlParser.SKIP_CHAR_ESCAPE.getFrom(options);
        extInlineStrong = FlexmarkHtmlParser.EXT_INLINE_STRONG.getFrom(options);
        extInlineEmphasis = FlexmarkHtmlParser.EXT_INLINE_EMPHASIS.getFrom(options);
        extInlineCode = FlexmarkHtmlParser.EXT_INLINE_CODE.getFrom(options);
        extInlineDel = FlexmarkHtmlParser.EXT_INLINE_DEL.getFrom(options);
        extInlineIns = FlexmarkHtmlParser.EXT_INLINE_INS.getFrom(options);
        extInlineSub = FlexmarkHtmlParser.EXT_INLINE_SUB.getFrom(options);
        extInlineSup = FlexmarkHtmlParser.EXT_INLINE_SUP.getFrom(options);
        extMath = FlexmarkHtmlParser.EXT_MATH.getFrom(options);
        extTables = FlexmarkHtmlParser.EXT_TABLES.getFrom(options);
        extInlineLink = FlexmarkHtmlParser.EXT_INLINE_LINK.getFrom(options);
        extInlineImage = FlexmarkHtmlParser.EXT_INLINE_IMAGE.getFrom(options);
        orderedListDelimiter = FlexmarkHtmlParser.ORDERED_LIST_DELIMITER.getFrom(options);
        unorderedListDelimiter = FlexmarkHtmlParser.UNORDERED_LIST_DELIMITER.getFrom(options);
        definitionMarkerSpaces = FlexmarkHtmlParser.DEFINITION_MARKER_SPACES.getFrom(options);
        minSetextHeadingMarkerLength = Utils.minLimit(FlexmarkHtmlParser.MIN_SETEXT_HEADING_MARKER_LENGTH.getFrom(options), 3);
        codeIndent = FlexmarkHtmlParser.CODE_INDENT.getFrom(options);
        eolInTitleAttribute = FlexmarkHtmlParser.EOL_IN_TITLE_ATTRIBUTE.getFrom(options);
        nbspText = FlexmarkHtmlParser.NBSP_TEXT.getFrom(options);
        thematicBreak = FlexmarkHtmlParser.THEMATIC_BREAK.getFrom(options);
        outputAttributesNamesRegex = FlexmarkHtmlParser.OUTPUT_ATTRIBUTES_NAMES_REGEX.getFrom(options);
        outputAttributesNamesRegexPattern = Pattern.compile(outputAttributesNamesRegex);
        outputIdAttributeRegex = FlexmarkHtmlParser.OUTPUT_ID_ATTRIBUTE_REGEX.getFrom(options);
        outputIdAttributeRegexPattern = Pattern.compile(outputIdAttributeRegex);
        tableCellAlignmentMap = FlexmarkHtmlParser.TABLE_CELL_ALIGNMENT_MAP.getFrom(options);
        tableOptions = new TableFormatOptions(options);
    }

    @Override
    public MutableDataHolder setIn(final MutableDataHolder dataHolder) {
        dataHolder.set(FlexmarkHtmlParser.LIST_CONTENT_INDENT, listContentIndent);
        dataHolder.set(FlexmarkHtmlParser.SETEXT_HEADINGS, setextHeadings);
        dataHolder.set(FlexmarkHtmlParser.OUTPUT_UNKNOWN_TAGS, outputUnknownTags);
        dataHolder.set(FlexmarkHtmlParser.TYPOGRAPHIC_QUOTES, typographicQuotes);
        dataHolder.set(FlexmarkHtmlParser.TYPOGRAPHIC_SMARTS, typographicSmarts);
        dataHolder.set(FlexmarkHtmlParser.OUTPUT_ATTRIBUTES_ID, outputAttributesIdAttr);
        dataHolder.set(FlexmarkHtmlParser.WRAP_AUTO_LINKS, wrapAutoLinks);
        dataHolder.set(FlexmarkHtmlParser.EXTRACT_AUTO_LINKS, extractAutoLinks);
        dataHolder.set(FlexmarkHtmlParser.RENDER_COMMENTS, renderComments);
        dataHolder.set(FlexmarkHtmlParser.DOT_ONLY_NUMERIC_LISTS, dotOnlyNumericLists);
        dataHolder.set(FlexmarkHtmlParser.COMMENT_ORIGINAL_NON_NUMERIC_LIST_ITEM, commentOriginalNonNumericListItem);
        dataHolder.set(FlexmarkHtmlParser.PRE_CODE_PRESERVE_EMPHASIS, preCodePreserveEmphasis);
        dataHolder.set(FlexmarkHtmlParser.LISTS_END_ON_DOUBLE_BLANK, listsEndOnDoubleBlank);
        dataHolder.set(FlexmarkHtmlParser.DIV_AS_PARAGRAPH, divAsParagraph);
        dataHolder.set(FlexmarkHtmlParser.BR_AS_PARA_BREAKS, brAsParaBreaks);
        dataHolder.set(FlexmarkHtmlParser.BR_AS_EXTRA_BLANK_LINES, brAsExtraBlankLines);
        dataHolder.set(FlexmarkHtmlParser.IGNORE_TABLE_HEADING_AFTER_ROWS, ignoreTableHeadingAfterRows);
        dataHolder.set(FlexmarkHtmlParser.ADD_TRAILING_EOL, addTrailingEol);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_STRONG, skipInlineStrong);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_EMPHASIS, skipInlineEmphasis);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_CODE, skipInlineCode);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_DEL, skipInlineDel);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_INS, skipInlineIns);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_SUB, skipInlineSub);
        dataHolder.set(FlexmarkHtmlParser.SKIP_INLINE_SUP, skipInlineSup);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_1, skipHeading1);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_2, skipHeading2);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_3, skipHeading3);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_4, skipHeading4);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_5, skipHeading5);
        dataHolder.set(FlexmarkHtmlParser.SKIP_HEADING_6, skipHeading6);
        dataHolder.set(FlexmarkHtmlParser.SKIP_ATTRIBUTES, skipAttributes);
        dataHolder.set(FlexmarkHtmlParser.SKIP_FENCED_CODE, skipFencedCode);
        dataHolder.set(FlexmarkHtmlParser.SKIP_LINKS, skipLinks);
        dataHolder.set(FlexmarkHtmlParser.SKIP_CHAR_ESCAPE, skipCharEscape);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_STRONG, extInlineStrong);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_EMPHASIS, extInlineEmphasis);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_CODE, extInlineCode);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_DEL, extInlineDel);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_INS, extInlineIns);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_SUB, extInlineSub);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_SUP, extInlineSup);
        dataHolder.set(FlexmarkHtmlParser.ORDERED_LIST_DELIMITER, orderedListDelimiter);
        dataHolder.set(FlexmarkHtmlParser.UNORDERED_LIST_DELIMITER, unorderedListDelimiter);
        dataHolder.set(FlexmarkHtmlParser.DEFINITION_MARKER_SPACES, definitionMarkerSpaces);
        dataHolder.set(FlexmarkHtmlParser.MIN_SETEXT_HEADING_MARKER_LENGTH, minSetextHeadingMarkerLength);
        dataHolder.set(FlexmarkHtmlParser.CODE_INDENT, codeIndent);
        dataHolder.set(FlexmarkHtmlParser.EOL_IN_TITLE_ATTRIBUTE, eolInTitleAttribute);
        dataHolder.set(FlexmarkHtmlParser.NBSP_TEXT, nbspText);
        dataHolder.set(FlexmarkHtmlParser.THEMATIC_BREAK, thematicBreak);
        dataHolder.set(FlexmarkHtmlParser.OUTPUT_ATTRIBUTES_NAMES_REGEX, outputAttributesNamesRegex);
        dataHolder.set(FlexmarkHtmlParser.TABLE_CELL_ALIGNMENT_MAP, tableCellAlignmentMap);
        dataHolder.set(FlexmarkHtmlParser.OUTPUT_ID_ATTRIBUTE_REGEX, outputIdAttributeRegex);
        dataHolder.set(FlexmarkHtmlParser.EXT_MATH, extMath);
        dataHolder.set(FlexmarkHtmlParser.EXT_TABLES, extTables);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_LINK, extInlineLink);
        dataHolder.set(FlexmarkHtmlParser.EXT_INLINE_IMAGE, extInlineImage);
        dataHolder.setFrom(tableOptions);
        return dataHolder;
    }
}
